<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cart_carousel-control-prev-icon</name>
   <tag></tag>
   <elementGuidId>ad83d909-990a-43b8-b9bd-869d90f27e85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.carousel-control-prev-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carouselExampleIndicators']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#carouselExampleIndicators >> internal:role=button[name=&quot;Previous&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e31d220f-2c91-4cd8-abf3-0dd4c9f9c387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-control-prev-icon</value>
      <webElementGuid>7b041fd5-fd6f-4fa4-8427-0784b0ab2632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9aabf16b-d681-4d02-be88-7938d02f46cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselExampleIndicators&quot;)/a[@class=&quot;carousel-control-prev&quot;]/span[@class=&quot;carousel-control-prev-icon&quot;]</value>
      <webElementGuid>8445619b-3744-429c-a3ba-707e452ffde7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselExampleIndicators']/a/span</value>
      <webElementGuid>bd27a1ce-c034-4cb8-bcc9-f8b322d92fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>aa2355e4-96ca-4847-a9a3-dadb8d8b8ec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
